import { TexterCommand } from "../utils";

export const mappings = {
    "q": ":regional_indicator_q:",
    "w": ":regional_indicator_w:",
    "e": ":regional_indicator_e:",
    "r": ":regional_indicator_r:",
    "t": ":regional_indicator_t:",
    "y": ":regional_indicator_y:",
    "u": ":regional_indicator_u:",
    "i": ":regional_indicator_i:",
    "o": ":regional_indicator_o:",
    "p": ":regional_indicator_p:",
    "a": ":regional_indicator_a:",
    "s": ":regional_indicator_s:",
    "d": ":regional_indicator_d:",
    "f": ":regional_indicator_f:",
    "g": ":regional_indicator_g:",
    "h": ":regional_indicator_h:",
    "j": ":regional_indicator_j:",
    "k": ":regional_indicator_k:",
    "l": ":regional_indicator_l:",
    "z": ":regional_indicator_z:",
    "x": ":regional_indicator_x:",
    "c": ":regional_indicator_c:",
    "v": ":regional_indicator_v:",
    "b": ":regional_indicator_b:",
    "n": ":regional_indicator_n:",
    "m": ":regional_indicator_m:",
    "Q": ":regional_indicator_q:",
    "W": ":regional_indicator_w:",
    "E": ":regional_indicator_e:",
    "R": ":regional_indicator_r:",
    "T": ":regional_indicator_t:",
    "Y": ":regional_indicator_y:",
    "U": ":regional_indicator_u:",
    "I": ":regional_indicator_i:",
    "O": ":regional_indicator_o:",
    "P": ":regional_indicator_p:",
    "A": ":regional_indicator_a:",
    "S": ":regional_indicator_s:",
    "D": ":regional_indicator_d:",
    "F": ":regional_indicator_f:",
    "G": ":regional_indicator_g:",
    "H": ":regional_indicator_h:",
    "J": ":regional_indicator_j:",
    "K": ":regional_indicator_k:",
    "L": ":regional_indicator_l:",
    "Z": ":regional_indicator_z:",
    "X": ":regional_indicator_x:",
    "C": ":regional_indicator_c:",
    "V": ":regional_indicator_v:",
    "B": ":regional_indicator_b:",
    "N": ":regional_indicator_n:",
    "M": ":regional_indicator_m:",
    "1": ":one:",
    "2": ":two:",
    "3": ":three:",
    "4": ":four:",
    "5": ":five:",
    "6": ":six:",
    "7": ":seven:",
    "8": ":eight:",
    "9": ":nine:",
    "0": ":zero:"
}

export const info: TexterCommand = {
    name: "emoji",
    aliases: ["emojify", "blockify"],
    description: "Turns your text into emoji blocks"
};