import { TexterCommand } from "../utils";

export const mappings = {
    "q": "ǫ",
    "w": "ᴡ",
    "e": "ᴇ",
    "r": "ʀ",
    "t": "ᴛ",
    "y": "ʏ",
    "u": "ᴜ",
    "i": "ɪ",
    "o": "ᴏ",
    "p": "ᴘ",
    "a": "ᴀ",
    "s": "s",
    "d": "ᴅ",
    "f": "ғ",
    "g": "ɢ",
    "h": "ʜ",
    "j": "ᴊ",
    "k": "ᴋ",
    "l": "ʟ",
    "z": "ᴢ",
    "x": "x",
    "c": "ᴄ",
    "v": "ᴠ",
    "b": "ʙ",
    "n": "ɴ",
    "m": "ᴍ",
    "Q": "ǫ",
    "W": "ᴡ",
    "E": "ᴇ",
    "R": "ʀ",
    "T": "ᴛ",
    "Y": "ʏ",
    "U": "ᴜ",
    "I": "ɪ",
    "O": "ᴏ",
    "P": "ᴘ",
    "A": "ᴀ",
    "S": "s",
    "D": "ᴅ",
    "F": "ғ",
    "G": "ɢ",
    "H": "ʜ",
    "J": "ᴊ",
    "K": "ᴋ",
    "L": "ʟ",
    "Z": "ᴢ",
    "X": "x",
    "C": "ᴄ",
    "V": "ᴠ",
    "B": "ʙ",
    "N": "ɴ",
    "M": "ᴍ"
}

export const info: TexterCommand = {
    name: "small",
    aliases: ["small"],
    description: "Replaces characters with small versions of them, making things ʟᴏᴏᴋ sᴍᴀʟʟ"
};