import { TexterCommand } from "../utils";

export const mappings = {
    "q": "ᑫ",
    "w": "ʷ",
    "e": "ᵉ",
    "r": "ʳ",
    "t": "ᵗ",
    "y": "ʸ",
    "u": "ᵘ",
    "i": "ᶦ",
    "o": "ᵒ",
    "p": "ᵖ",
    "a": "ᵃ",
    "s": "ˢ",
    "d": "ᵈ",
    "f": "ᶠ",
    "g": "ᵍ",
    "h": "ʰ",
    "j": "ʲ",
    "k": "ᵏ",
    "l": "ˡ",
    "z": "ᶻ",
    "x": "ˣ",
    "c": "ᶜ",
    "v": "ᵛ",
    "b": "ᵇ",
    "n": "ⁿ",
    "m": "ᵐ",
    "Q": "ᑫ",
    "W": "ʷ",
    "E": "ᵉ",
    "R": "ʳ",
    "T": "ᵗ",
    "Y": "ʸ",
    "U": "ᵘ",
    "I": "ᶦ",
    "O": "ᵒ",
    "P": "ᵖ",
    "A": "ᵃ",
    "S": "ˢ",
    "D": "ᵈ",
    "F": "ᶠ",
    "G": "ᵍ",
    "H": "ʰ",
    "J": "ʲ",
    "K": "ᵏ",
    "L": "ˡ",
    "Z": "ᶻ",
    "X": "ˣ",
    "C": "ᶜ",
    "V": "ᵛ",
    "B": "ᵇ",
    "N": "ⁿ",
    "M": "ᵐ",
    "1": "¹",
    "2": "²",
    "3": "³",
    "4": "⁴",
    "5": "⁵",
    "6": "⁶",
    "7": "⁷",
    "8": "⁸",
    "9": "⁹",
    "0": "⁰"
}

export const info: TexterCommand = {
    name: "tiny",
    aliases: ["tiny"],
    description: "Replaces characters with tiny versions of them, making things ˡᵒᵒᵏ ᵗᶦⁿʸ"
};