import { TexterCommand } from "../utils";

export const mappings = {
    "q": "b",
    "w": "ʍ",
    "e": "ǝ",
    "r": "ɹ",
    "t": "ʇ",
    "y": "ʎ",
    "u": "n",
    "i": "ᴉ",
    "p": "d",
    "a": "ɐ",
    "s": "s",
    "d": "p",
    "f": "ɟ",
    "g": "ɓ",
    "h": "ɥ",
    "j": "ſ",
    "k": "ʞ",
    "l": "ๅ",
    "z": "z",
    "x": "x",
    "c": "ɔ",
    "v": "ʌ",
    "b": "q",
    "n": "u",
    "m": "ɯ",
    "Q": "Ὸ",
    "W": "M",
    "E": "Ǝ",
    "R": "ꓤ",
    "T": "ꓕ",
    "Y": "⅄",
    "U": "ꓵ",
    "I": "I",
    "O": "O",
    "P": "ꓒ",
    "A": "Ɐ",
    "S": "S",
    "D": "ꓷ",
    "F": "ꓞ",
    "G": "ꓨ",
    "H": "H",
    "J": "ſ",
    "K": "ꓘ",
    "L": "ꓶ",
    "Z": "Z",
    "X": "X",
    "C": "ꓛ",
    "V": "ꓥ",
    "B": "ꓭ",
    "N": "N",
    "M": "W",
    "1": "Ɩ",
    "2": "Շ",
    "3": "Ɛ",
    "4": "h",
    "5": "૬",
    "6": "9",
    "7": "L",
    "8": "8",
    "9": "6",
    "0": "0"
}

export const info: TexterCommand = {
    name: "upsidedown",
    aliases: ["upsidedown", "flip"],
    description: "Flips your text upside down"
};